name: Android CI

on: push:
pull_request:
 workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK & NDK
      uses: android-actions/setup-android@v3

    # If the build requires a specific NDK version, uncomment and specify it below:
    # - name: Install NDK
    #   run: sdkmanager --install "ndk;25.1.8937393"

    - name: Change to Android directory & Grant Execute Permissions
      run: |
        cd android
        chmod +x gradlew

    - name: Build with Gradle
      run: |
        cd android
        ./gradlew assembleDebug
